version: "3"

services:
  pywps:
    build:
      context: pywps
    ports:
      - "5000"
    volumes:
      - ./pywps:/pywps
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pywps
    ports:
      - "80:80"